apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guarduim-operator-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: guarduim
roleRef:
  kind: ClusterRole
  name: guarduim-controller-role  # Should match the ClusterRole name
  apiGroup: rbac.authorization.k8s.io
