apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: guarduims.guard.example.com
spec:
  group: guard.example.com
  names:
    kind: Guarduim
    plural: guarduims
    singular: guarduim
    shortNames:
    - gu
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                threshold:
                  type: integer
                failures:
                  type: integer
            status:
              type: object
              properties:
                isBlocked:
                  type: boolean
                failedAttempts:
                  type: integer
