# permissions for end users to view guarduims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: guarduim
    app.kubernetes.io/managed-by: kustomize
  name: guarduim-viewer-role
rules:
- apiGroups:
  - auth.example.com
  resources:
  - guarduims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.example.com
  resources:
  - guarduims/status
  verbs:
  - get
